CREATE TABLE IF NOT EXISTS silver_tumor_pathology (
    patient_id                     VARCHAR PRIMARY KEY REFERENCES silver_patients(patient_id) ON DELETE CASCADE,
    cancer_type                    VARCHAR NOT NULL,
    cancer_type_detailed           VARCHAR,
    cellularity                    VARCHAR,
    neoplasm_histologic_grade      NUMERIC,
    tumor_other_histologic_subtype VARCHAR,
    tumor_size                     NUMERIC,
    tumor_stage                    NUMERIC,
    oncotree_code                  VARCHAR,
    lymph_nodes_examined_positive  NUMERIC,
    mutation_count                 NUMERIC,
    nottingham_prognostic_index    NUMERIC,
    pam50_subtype                  VARCHAR,
    integrative_cluster            VARCHAR,
    three_gene_subtype             VARCHAR,
    er_status                      VARCHAR,
    er_status_ihc                  VARCHAR,
    her2_status                    VARCHAR,
    her2_status_snp6               VARCHAR,
    pr_status                      VARCHAR,
    primary_tumor_laterality       VARCHAR,
    receptor_profile               VARCHAR,

    CONSTRAINT chk_tumor_size CHECK (tumor_size IS NULL OR tumor_size > 0),
    CONSTRAINT chk_npi_range CHECK (nottingham_prognostic_index IS NULL OR nottingham_prognostic_index BETWEEN 1.0 AND 7.0),
    CONSTRAINT chk_tumor_stage_range CHECK (tumor_stage IS NULL OR tumor_stage BETWEEN 0 AND 4),
    CONSTRAINT chk_er_status CHECK (er_status IS NULL OR er_status IN ('Positive', 'Negative')),
    CONSTRAINT chk_pr_status CHECK (pr_status IS NULL OR pr_status IN ('Positive', 'Negative')),
    CONSTRAINT chk_her2_status CHECK (her2_status IS NULL OR her2_status IN ('Positive', 'Negative'))
);